--- a/arch/arm/mach-exynos/Makefile
+++ b/arch/arm/mach-exynos/Makefile
@@ -8,7 +8,18 @@
 obj-$(CONFIG_EXYNOS_CPU_SUSPEND) += pm.o sleep.o
 obj-$(CONFIG_PM_SLEEP)		+= suspend.o
 
+obj-$(CONFIG_BUSFREQ_OPP)	+= dev.o
+
 obj-$(CONFIG_SMP)		+= platsmp.o headsmp.o
 
 obj-$(CONFIG_EXYNOS_MCPM)	+= mcpm-exynos.o
 CFLAGS_mcpm-exynos.o		+= -march=armv7-a
+
+obj-$(CONFIG_SEC_MODEM_GAIA)		+= board-gaia-modems.o
+obj-$(CONFIG_SEC_MODEM_M1)		+= board-c1-modems.o
+obj-$(CONFIG_SEC_MODEM_C1)		+= board-c1-modems.o
+obj-$(CONFIG_SEC_MODEM_C1_LGT)		+= board-c1lgt-modems.o
+obj-$(CONFIG_SEC_MODEM_P8LTE)		+= board-p8ltevzw-modems.o
+
+obj-$(CONFIG_MSM_SUBSYSTEM_RESTART)	+= subsystem_restart.o
+
